alias tmux='tmux -u'

# Source Prezto.
#set -x
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  set +x
fi

# Customize to your needs...
setopt nosharehistory

source ~/.bashrc-exports
source ~/.bashrc-aliases
source ~/.bashrc-functions
source ~/.bashrc-privateexports
source ~/.bashrc-privatealiases
source ~/.bashrc-privatefunctions
source ~/bin/lp.sh
#export LD_LIBRARY_PATH=
xauth nlist :0 | sed -e 's/^..../ffff/'  | xauth -f /tmp/.docker.xauth nmerge - &

[[ -f ${HOME}/bin/xrandr.sh ]] && ${HOME}/bin/xrandr.sh
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/chous/.sdkman"
[[ -s "/home/chous/.sdkman/bin/sdkman-init.sh" ]] && source "/home/chous/.sdkman/bin/sdkman-init.sh"
#
